### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by CatchMeIfYouCanLMAO** [CrazyOutOff/rinaorc#2]
Bonjour comment je peux installer ceci dans mon code en JS ?

**Comment by BonnetAdam** [comment]
Bonjour @CatchMeIfYouCanLMAO, tu peux utilser Node.JS et mettre ```npm i rinaorc```dans ton terminal ensuite faire ```const rinaorc = require('rinaorc')```. Ou sinon tu peux copier le index.js le mettre dans t'es fichier et l'appeler simplement depuis ton js ;) . Bonne chance à toi et bon code.

**Comment by CatchMeIfYouCanLMAO** [comment]
Merci beaucoup, je comprends mieux comment je peux m'y prendre.
